import type { INodeProperties } from 'n8n-workflow';

// ──────────────────────────────────────────────────────────────
// Resource selector
// ──────────────────────────────────────────────────────────────

export const resourceField: INodeProperties = {
	displayName: 'Resource',
	name: 'resource',
	type: 'options',
	noDataExpression: true,
	options: [
		{ name: 'Midjourney', value: 'midjourney' },
		{ name: 'Dreamina', value: 'dreamina' },
		{ name: 'Kling', value: 'kling' },
		{ name: 'Runway', value: 'runway' },
		{ name: 'PixVerse', value: 'pixverse' },
		{ name: 'MiniMax', value: 'minimax' },
		{ name: 'InsightFaceSwap', value: 'insightfaceswap' },
		{ name: 'Google Flow', value: 'googleFlow' },
	],
	default: 'midjourney',
};

// ──────────────────────────────────────────────────────────────
// Midjourney operations + fields
// ──────────────────────────────────────────────────────────────

export const midjourneyOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['midjourney'] } },
	options: [
		{ name: 'Imagine', value: 'imagine', description: 'Create an image from a prompt', action: 'Create an image from a prompt' },
		{ name: 'Button', value: 'button', description: 'Click a button (upscale, variation, etc.)', action: 'Click a button' },
		{ name: 'Describe', value: 'describe', description: 'Describe an image', action: 'Describe an image' },
		{ name: 'Blend', value: 'blend', description: 'Blend multiple images together', action: 'Blend images' },
		{ name: 'Seed', value: 'seed', description: 'Get seed value for a completed job', action: 'Get seed value' },
		{ name: 'Settings', value: 'settings', description: 'Apply settings to an account', action: 'Apply settings' },
		{ name: 'Remix', value: 'remix', description: 'Remix a job with a new prompt', action: 'Remix a job' },
		{ name: 'Variability', value: 'variability', description: 'Toggle variability for a job', action: 'Toggle variability' },
		{ name: 'Get Job', value: 'getJob', description: 'Get job status', action: 'Get job status' },
		{ name: 'List Jobs', value: 'listJobs', description: 'List jobs', action: 'List jobs' },
		{ name: 'Cancel Job', value: 'cancelJob', description: 'Cancel a running job', action: 'Cancel a job' },
		{ name: 'List Accounts', value: 'listAccounts', description: 'List all Midjourney accounts', action: 'List accounts' },
	],
	default: 'imagine',
};

export const midjourneyFields: INodeProperties[] = [
	// imagine
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The image prompt for Midjourney',
		displayOptions: { show: { resource: ['midjourney'], operation: ['imagine'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Midjourney account to use',
		displayOptions: { show: { resource: ['midjourney'], operation: ['imagine'] } },
	},
	{
		displayName: 'Reply URL',
		name: 'replyUrl',
		type: 'string',
		default: '',
		description: 'Webhook URL for job completion notification',
		displayOptions: { show: { resource: ['midjourney'], operation: ['imagine'] } },
	},
	{
		displayName: 'Reply Ref',
		name: 'replyRef',
		type: 'string',
		default: '',
		description: 'Custom reference passed back in webhook',
		displayOptions: { show: { resource: ['midjourney'], operation: ['imagine'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['midjourney'], operation: ['imagine'] } },
	},

	// button
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'Parent job ID',
		displayOptions: { show: { resource: ['midjourney'], operation: ['button'] } },
	},
	{
		displayName: 'Button',
		name: 'button',
		type: 'string',
		required: true,
		default: '',
		description: 'Button label (e.g. "U1", "V1", "Upscale (2x)", "Vary (Strong)", "Zoom Out 2x", "Make Square", "🔄")',
		displayOptions: { show: { resource: ['midjourney'], operation: ['button'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Midjourney account to use',
		displayOptions: { show: { resource: ['midjourney'], operation: ['button'] } },
	},
	{
		displayName: 'Reply URL',
		name: 'replyUrl',
		type: 'string',
		default: '',
		description: 'Webhook URL for job completion notification',
		displayOptions: { show: { resource: ['midjourney'], operation: ['button'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['midjourney'], operation: ['button'] } },
	},

	// describe
	{
		displayName: 'Image URL',
		name: 'url',
		type: 'string',
		default: '',
		description: 'URL of the image to describe',
		displayOptions: { show: { resource: ['midjourney'], operation: ['describe'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Midjourney account to use',
		displayOptions: { show: { resource: ['midjourney'], operation: ['describe'] } },
	},
	{
		displayName: 'Reply URL',
		name: 'replyUrl',
		type: 'string',
		default: '',
		description: 'Webhook URL for job completion notification',
		displayOptions: { show: { resource: ['midjourney'], operation: ['describe'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['midjourney'], operation: ['describe'] } },
	},

	// blend
	{
		displayName: 'Image URLs',
		name: 'blendUrls',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated image URLs to blend (2-5 images)',
		displayOptions: { show: { resource: ['midjourney'], operation: ['blend'] } },
	},
	{
		displayName: 'Dimensions',
		name: 'dimensions',
		type: 'options',
		options: [
			{ name: 'Portrait', value: 'Portrait' },
			{ name: 'Square', value: 'Square' },
			{ name: 'Landscape', value: 'Landscape' },
		],
		default: 'Square',
		description: 'Output image dimensions',
		displayOptions: { show: { resource: ['midjourney'], operation: ['blend'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Midjourney account to use',
		displayOptions: { show: { resource: ['midjourney'], operation: ['blend'] } },
	},
	{
		displayName: 'Reply URL',
		name: 'replyUrl',
		type: 'string',
		default: '',
		description: 'Webhook URL for job completion notification',
		displayOptions: { show: { resource: ['midjourney'], operation: ['blend'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['midjourney'], operation: ['blend'] } },
	},

	// seed
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'Job ID to get the seed value for',
		displayOptions: { show: { resource: ['midjourney'], operation: ['seed'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Midjourney account to use',
		displayOptions: { show: { resource: ['midjourney'], operation: ['seed'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['midjourney'], operation: ['seed'] } },
	},

	// settings
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Midjourney account to use',
		displayOptions: { show: { resource: ['midjourney'], operation: ['settings'] } },
	},
	{
		displayName: 'Payload',
		name: 'payload',
		type: 'json',
		default: '{}',
		description: 'Settings object to apply (raw JSON)',
		displayOptions: { show: { resource: ['midjourney'], operation: ['settings'] } },
	},

	// remix
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'Job ID to remix',
		displayOptions: { show: { resource: ['midjourney'], operation: ['remix'] } },
	},
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'New prompt for the remix',
		displayOptions: { show: { resource: ['midjourney'], operation: ['remix'] } },
	},
	{
		displayName: 'Button',
		name: 'button',
		type: 'string',
		required: true,
		default: '',
		description: 'Which variation button to remix (e.g. "V1")',
		displayOptions: { show: { resource: ['midjourney'], operation: ['remix'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Midjourney account to use',
		displayOptions: { show: { resource: ['midjourney'], operation: ['remix'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['midjourney'], operation: ['remix'] } },
	},

	// variability
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'Job ID to toggle variability',
		displayOptions: { show: { resource: ['midjourney'], operation: ['variability'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Midjourney account to use',
		displayOptions: { show: { resource: ['midjourney'], operation: ['variability'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['midjourney'], operation: ['variability'] } },
	},

	// getJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The job ID to retrieve',
		displayOptions: { show: { resource: ['midjourney'], operation: ['getJob'] } },
	},

	// listJobs
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Filter jobs by account',
		displayOptions: { show: { resource: ['midjourney'], operation: ['listJobs'] } },
	},
	{
		displayName: 'Status',
		name: 'status',
		type: 'options',
		options: [
			{ name: 'All', value: '' },
			{ name: 'Created', value: 'created' },
			{ name: 'Started', value: 'started' },
			{ name: 'Moderated', value: 'moderated' },
			{ name: 'Completed', value: 'completed' },
			{ name: 'Failed', value: 'failed' },
		],
		default: '',
		description: 'Filter jobs by status',
		displayOptions: { show: { resource: ['midjourney'], operation: ['listJobs'] } },
	},

	// cancelJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The job ID to cancel',
		displayOptions: { show: { resource: ['midjourney'], operation: ['cancelJob'] } },
	},
];

// ──────────────────────────────────────────────────────────────
// Dreamina operations + fields
// ──────────────────────────────────────────────────────────────

export const dreaminaOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['dreamina'] } },
	options: [
		{ name: 'Generate Image', value: 'generateImage', description: 'Generate an image from a prompt', action: 'Generate an image' },
		{ name: 'Generate Video', value: 'generateVideo', description: 'Generate a video from a prompt', action: 'Generate a video' },
		{ name: 'Upscale Image', value: 'upscaleImage', description: 'Upscale a generated image', action: 'Upscale an image' },
		{ name: 'Get Image Job', value: 'getImageJob', description: 'Get image job status', action: 'Get image job' },
		{ name: 'Get Video Job', value: 'getVideoJob', description: 'Get video job status', action: 'Get video job' },
		{ name: 'List Assets', value: 'listAssets', description: 'List assets for an account', action: 'List assets' },
		{ name: 'Delete Asset', value: 'deleteAsset', description: 'Delete an asset', action: 'Delete asset' },
		{ name: 'Cancel Job', value: 'cancelJob', description: 'Cancel a running job', action: 'Cancel a job' },
		{ name: 'Add Account', value: 'addAccount', description: 'Add a Dreamina account', action: 'Add account' },
		{ name: 'Get Account', value: 'getAccount', description: 'Get account details and claim daily credits', action: 'Get account' },
		{ name: 'List Accounts', value: 'listAccounts', description: 'List all Dreamina accounts', action: 'List accounts' },
		{ name: 'Delete Account', value: 'deleteAccount', description: 'Delete a Dreamina account', action: 'Delete account' },
	],
	default: 'generateImage',
};

export const dreaminaFields: INodeProperties[] = [
	// generateImage
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The image prompt',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Seedream 5.0 Lite', value: 'seedream-5.0-lite' },
			{ name: 'Seedream 4.6', value: 'seedream-4.6' },
			{ name: 'Seedream 4.5', value: 'seedream-4.5' },
			{ name: 'Seedream 4.1', value: 'seedream-4.1' },
			{ name: 'Seedream 4.0', value: 'seedream-4.0' },
			{ name: 'Nano Banana', value: 'nano-banana' },
			{ name: 'Seedream 3.0', value: 'seedream-3.0' },
		],
		default: 'seedream-4.0',
		description: 'Image generation model',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Ratio',
		name: 'ratio',
		type: 'options',
		options: [
			{ name: '1:1', value: '1:1' },
			{ name: '16:9', value: '16:9' },
			{ name: '9:16', value: '9:16' },
			{ name: '4:3', value: '4:3' },
			{ name: '3:4', value: '3:4' },
			{ name: '3:2', value: '3:2' },
			{ name: '2:3', value: '2:3' },
			{ name: '21:9', value: '21:9' },
			{ name: '9:21', value: '9:21' },
		],
		default: '1:1',
		description: 'Image aspect ratio',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Resolution',
		name: 'resolution',
		type: 'options',
		options: [
			{ name: '2K', value: '2k' },
			{ name: '1K', value: '1k' },
			{ name: 'Auto', value: 'auto' },
		],
		default: '2k',
		description: 'Image resolution',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Seed',
		name: 'seed',
		type: 'number',
		default: 0,
		description: 'Seed value for reproducibility (0 = random)',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Image Ref 1',
		name: 'imageRef_1',
		type: 'string',
		default: '',
		description: 'Asset reference from a previous image (image-to-image reference)',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Image Ref 2',
		name: 'imageRef_2',
		type: 'string',
		default: '',
		description: 'Second image reference',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Image Ref 3',
		name: 'imageRef_3',
		type: 'string',
		default: '',
		description: 'Third image reference',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Dreamina account to use',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Reply URL',
		name: 'replyUrl',
		type: 'string',
		default: '',
		description: 'Webhook URL for job completion notification',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateImage'] } },
	},

	// generateVideo
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The video prompt',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Seedance 2.0', value: 'seedance-2.0' },
			{ name: 'Seedance 1.5 Pro', value: 'seedance-1.5-pro' },
			{ name: 'Seedance 1.0 Mini', value: 'seedance-1.0-mini' },
		],
		default: 'seedance-2.0',
		description: 'Video generation model',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Ratio',
		name: 'ratio',
		type: 'options',
		options: [
			{ name: '16:9', value: '16:9' },
			{ name: '9:16', value: '9:16' },
			{ name: '1:1', value: '1:1' },
		],
		default: '16:9',
		description: 'Video aspect ratio',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Duration',
		name: 'duration',
		type: 'options',
		options: [
			{ name: '5 Seconds', value: 5 },
			{ name: '10 Seconds', value: 10 },
		],
		default: 5,
		description: 'Video duration in seconds',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'First Frame Ref',
		name: 'firstFrameRef',
		type: 'string',
		default: '',
		description: 'Asset reference from a previous image job to use as first frame',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Dreamina account to use',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Reply URL',
		name: 'replyUrl',
		type: 'string',
		default: '',
		description: 'Webhook URL for job completion notification',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['dreamina'], operation: ['generateVideo'] } },
	},

	// upscaleImage
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'Source image job ID to upscale',
		displayOptions: { show: { resource: ['dreamina'], operation: ['upscaleImage'] } },
	},
	{
		displayName: 'Image Index',
		name: 'imageIndex',
		type: 'number',
		default: 0,
		description: 'Index of the image to upscale from the job',
		displayOptions: { show: { resource: ['dreamina'], operation: ['upscaleImage'] } },
	},
	{
		displayName: 'Resolution',
		name: 'resolution',
		type: 'options',
		options: [
			{ name: '4K', value: '4k' },
			{ name: '2K', value: '2k' },
		],
		default: '4k',
		description: 'Upscaled image resolution',
		displayOptions: { show: { resource: ['dreamina'], operation: ['upscaleImage'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Dreamina account to use',
		displayOptions: { show: { resource: ['dreamina'], operation: ['upscaleImage'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['dreamina'], operation: ['upscaleImage'] } },
	},

	// getImageJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The image job ID to retrieve',
		displayOptions: { show: { resource: ['dreamina'], operation: ['getImageJob'] } },
	},

	// getVideoJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The video job ID to retrieve',
		displayOptions: { show: { resource: ['dreamina'], operation: ['getVideoJob'] } },
	},

	// listAssets
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		required: true,
		default: '',
		description: 'Account to list assets for',
		displayOptions: { show: { resource: ['dreamina'], operation: ['listAssets'] } },
	},
	{
		displayName: 'Count',
		name: 'count',
		type: 'number',
		default: 20,
		description: 'Number of assets to return (max 100)',
		displayOptions: { show: { resource: ['dreamina'], operation: ['listAssets'] } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'string',
		default: '',
		description: 'Pagination cursor',
		displayOptions: { show: { resource: ['dreamina'], operation: ['listAssets'] } },
	},

	// deleteAsset
	{
		displayName: 'Asset ID',
		name: 'assetId',
		type: 'string',
		required: true,
		default: '',
		description: 'The asset ID to delete',
		displayOptions: { show: { resource: ['dreamina'], operation: ['deleteAsset'] } },
	},

	// cancelJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The job ID to cancel',
		displayOptions: { show: { resource: ['dreamina'], operation: ['cancelJob'] } },
	},

	// addAccount
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		required: true,
		default: '',
		description: 'Account email address',
		displayOptions: { show: { resource: ['dreamina'], operation: ['addAccount'] } },
	},
	{
		displayName: 'Password',
		name: 'password',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		description: 'Account password',
		displayOptions: { show: { resource: ['dreamina'], operation: ['addAccount'] } },
	},
	{
		displayName: 'Region',
		name: 'region',
		type: 'options',
		options: [
			{ name: 'US', value: 'US' },
		],
		default: 'US',
		description: 'Account region',
		displayOptions: { show: { resource: ['dreamina'], operation: ['addAccount'] } },
	},
	{
		displayName: 'Dry Run',
		name: 'dryRun',
		type: 'boolean',
		default: false,
		description: 'Whether to verify only without saving',
		displayOptions: { show: { resource: ['dreamina'], operation: ['addAccount'] } },
	},

	// getAccount
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		required: true,
		default: '',
		description: 'Account identifier (also claims daily credits)',
		displayOptions: { show: { resource: ['dreamina'], operation: ['getAccount'] } },
	},

	// deleteAccount
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		required: true,
		default: '',
		description: 'Account identifier to delete',
		displayOptions: { show: { resource: ['dreamina'], operation: ['deleteAccount'] } },
	},
];

// ──────────────────────────────────────────────────────────────
// Kling operations + fields
// ──────────────────────────────────────────────────────────────

export const klingOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['kling'] } },
	options: [
		{ name: 'Text to Video', value: 'textToVideo', description: 'Generate video from text prompt', action: 'Generate video from text' },
		{ name: 'Image to Video', value: 'imageToVideo', description: 'Generate video from image', action: 'Generate video from image' },
		{ name: 'Image to Video Effects', value: 'imageToVideoEffects', description: 'Apply effects to image video', action: 'Apply image effects' },
		{ name: 'Extend Video', value: 'extendVideo', description: 'Extend a video', action: 'Extend video' },
		{ name: 'Lip Sync', value: 'lipSync', description: 'Add lip sync to a video', action: 'Lip sync video' },
		{ name: 'Add Sound', value: 'addSound', description: 'Add sound to a video', action: 'Add sound to video' },
		{ name: 'Motion Create', value: 'motionCreate', description: 'Create motion from image', action: 'Create motion' },
		{ name: 'Text to Image (KOLORS)', value: 'textToImage', description: 'Generate image from text (KOLORS)', action: 'Generate image from text' },
		{ name: 'Omni Image', value: 'omniImage', description: 'Generate image with Omni model', action: 'Generate omni image' },
		{ name: 'Virtual Try On', value: 'virtualTryOn', description: 'Virtual clothing try-on', action: 'Virtual try on' },
		{ name: 'Recognize Faces', value: 'recognizeFaces', description: 'Recognize faces in an image', action: 'Recognize faces' },
		{ name: 'Upscale Image', value: 'upscaleImage', description: 'Upscale an image', action: 'Upscale image' },
		{ name: 'Text to Speech', value: 'textToSpeech', description: 'Convert text to speech', action: 'Text to speech' },
		{ name: 'Avatar Video', value: 'avatarVideo', description: 'Create avatar video', action: 'Create avatar video' },
		{ name: 'Get Task', value: 'getTask', description: 'Get task status', action: 'Get task status' },
		{ name: 'List Tasks', value: 'listTasks', description: 'List tasks', action: 'List tasks' },
		{ name: 'Cancel Task', value: 'cancelTask', description: 'Cancel a running task', action: 'Cancel a task' },
		{ name: 'List Effects', value: 'listEffects', description: 'List available video effects', action: 'List effects' },
		{ name: 'List Motions', value: 'listMotions', description: 'List available motions', action: 'List motions' },
		{ name: 'List Avatars', value: 'listAvatars', description: 'List available avatars', action: 'List avatars' },
		{ name: 'List TTS Voices', value: 'listTtsVoices', description: 'List available TTS voices', action: 'List TTS voices' },
		{ name: 'Upload Asset', value: 'uploadAsset', description: 'Upload an asset to Kling', action: 'Upload asset' },
		{ name: 'List Assets', value: 'listAssets', description: 'List assets', action: 'List assets' },
		{ name: 'List Accounts', value: 'listAccounts', description: 'List all Kling accounts', action: 'List accounts' },
	],
	default: 'textToVideo',
};

export const klingFields: INodeProperties[] = [
	// textToVideo
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The video prompt',
		displayOptions: { show: { resource: ['kling'], operation: ['textToVideo'] } },
	},
	{
		displayName: 'Negative Prompt',
		name: 'negative_prompt',
		type: 'string',
		default: '',
		description: 'What to avoid in the video',
		displayOptions: { show: { resource: ['kling'], operation: ['textToVideo'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Kling V3', value: 'kling-v3' },
			{ name: 'Kling O1', value: 'kling-o1' },
			{ name: 'Kling V2.6', value: 'kling-v2.6' },
			{ name: 'Kling V2.5', value: 'kling-v2.5' },
			{ name: 'Kling V2.1', value: 'kling-v2.1' },
			{ name: 'Kling V2.0', value: 'kling-v2.0' },
			{ name: 'Kling V1.6', value: 'kling-v1.6' },
			{ name: 'Kling V1.5', value: 'kling-v1.5' },
		],
		default: 'kling-v2.6',
		description: 'Video generation model',
		displayOptions: { show: { resource: ['kling'], operation: ['textToVideo'] } },
	},
	{
		displayName: 'Mode',
		name: 'mode',
		type: 'options',
		options: [
			{ name: 'Standard', value: 'std' },
			{ name: 'Professional', value: 'pro' },
			{ name: 'Master', value: 'master' },
		],
		default: 'std',
		description: 'Generation mode',
		displayOptions: { show: { resource: ['kling'], operation: ['textToVideo'] } },
	},
	{
		displayName: 'Aspect Ratio',
		name: 'aspect_ratio',
		type: 'options',
		options: [
			{ name: '16:9', value: '16:9' },
			{ name: '9:16', value: '9:16' },
			{ name: '1:1', value: '1:1' },
		],
		default: '16:9',
		description: 'Video aspect ratio',
		displayOptions: { show: { resource: ['kling'], operation: ['textToVideo'] } },
	},
	{
		displayName: 'Duration',
		name: 'duration',
		type: 'options',
		options: [
			{ name: '5 Seconds', value: '5' },
			{ name: '10 Seconds', value: '10' },
		],
		default: '5',
		description: 'Video duration',
		displayOptions: { show: { resource: ['kling'], operation: ['textToVideo'] } },
	},
	{
		displayName: 'CFG Scale',
		name: 'cfg_scale',
		type: 'number',
		default: 0.5,
		description: 'CFG scale (0-1)',
		displayOptions: { show: { resource: ['kling'], operation: ['textToVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['textToVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['textToVideo'] } },
	},

	// imageToVideo
	{
		displayName: 'Image URL',
		name: 'image_url',
		type: 'string',
		required: true,
		default: '',
		description: 'Input image URL for video generation',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideo'] } },
	},
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		default: '',
		description: 'Optional text prompt to guide the video',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideo'] } },
	},
	{
		displayName: 'Negative Prompt',
		name: 'negative_prompt',
		type: 'string',
		default: '',
		description: 'What to avoid in the video',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideo'] } },
	},
	{
		displayName: 'Tail Image URL',
		name: 'tail_image_url',
		type: 'string',
		default: '',
		description: 'Last frame image URL',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideo'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Kling V3', value: 'kling-v3' },
			{ name: 'Kling O1', value: 'kling-o1' },
			{ name: 'Kling V2.6', value: 'kling-v2.6' },
			{ name: 'Kling V2.5', value: 'kling-v2.5' },
			{ name: 'Kling V2.1', value: 'kling-v2.1' },
			{ name: 'Kling V2.0', value: 'kling-v2.0' },
			{ name: 'Kling V1.6', value: 'kling-v1.6' },
			{ name: 'Kling V1.5', value: 'kling-v1.5' },
		],
		default: 'kling-v2.6',
		description: 'Video generation model',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideo'] } },
	},
	{
		displayName: 'Mode',
		name: 'mode',
		type: 'options',
		options: [
			{ name: 'Standard', value: 'std' },
			{ name: 'Professional', value: 'pro' },
			{ name: 'Master', value: 'master' },
		],
		default: 'std',
		description: 'Generation mode',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideo'] } },
	},
	{
		displayName: 'Duration',
		name: 'duration',
		type: 'options',
		options: [
			{ name: '5 Seconds', value: '5' },
			{ name: '10 Seconds', value: '10' },
		],
		default: '5',
		description: 'Video duration',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideo'] } },
	},
	{
		displayName: 'CFG Scale',
		name: 'cfg_scale',
		type: 'number',
		default: 0.5,
		description: 'CFG scale (0-1)',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideo'] } },
	},

	// imageToVideoEffects
	{
		displayName: 'Image URL',
		name: 'image_url',
		type: 'string',
		required: true,
		default: '',
		description: 'Input image URL',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideoEffects'] } },
	},
	{
		displayName: 'Effect ID',
		name: 'effect_id',
		type: 'string',
		required: true,
		default: '',
		description: 'Effect ID from List Effects operation',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideoEffects'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideoEffects'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['imageToVideoEffects'] } },
	},

	// extendVideo
	{
		displayName: 'Task ID',
		name: 'task_id',
		type: 'string',
		required: true,
		default: '',
		description: 'Source video task ID',
		displayOptions: { show: { resource: ['kling'], operation: ['extendVideo'] } },
	},
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		default: '',
		description: 'Optional prompt for extension',
		displayOptions: { show: { resource: ['kling'], operation: ['extendVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['extendVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['extendVideo'] } },
	},

	// lipSync
	{
		displayName: 'Task ID',
		name: 'task_id',
		type: 'string',
		required: true,
		default: '',
		description: 'Source video task ID',
		displayOptions: { show: { resource: ['kling'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Audio URL',
		name: 'audio_url',
		type: 'string',
		default: '',
		description: 'Audio URL for lip sync',
		displayOptions: { show: { resource: ['kling'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		default: '',
		description: 'Text for TTS lip sync',
		displayOptions: { show: { resource: ['kling'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Voice ID',
		name: 'voice_id',
		type: 'string',
		default: '',
		description: 'Voice ID from List TTS Voices',
		displayOptions: { show: { resource: ['kling'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['lipSync'] } },
	},

	// addSound
	{
		displayName: 'Task ID',
		name: 'task_id',
		type: 'string',
		required: true,
		default: '',
		description: 'Source video task ID',
		displayOptions: { show: { resource: ['kling'], operation: ['addSound'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['addSound'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['addSound'] } },
	},

	// motionCreate
	{
		displayName: 'Image URL',
		name: 'image_url',
		type: 'string',
		required: true,
		default: '',
		description: 'Input image URL',
		displayOptions: { show: { resource: ['kling'], operation: ['motionCreate'] } },
	},
	{
		displayName: 'Motion ID',
		name: 'motion_id',
		type: 'string',
		required: true,
		default: '',
		description: 'Motion ID from List Motions operation',
		displayOptions: { show: { resource: ['kling'], operation: ['motionCreate'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Kling V3', value: 'kling-v3' },
			{ name: 'Kling V2.6', value: 'kling-v2.6' },
		],
		default: 'kling-v2.6',
		description: 'Model version',
		displayOptions: { show: { resource: ['kling'], operation: ['motionCreate'] } },
	},
	{
		displayName: 'Duration',
		name: 'duration',
		type: 'options',
		options: [
			{ name: '5 Seconds', value: '5' },
			{ name: '10 Seconds', value: '10' },
		],
		default: '5',
		description: 'Video duration',
		displayOptions: { show: { resource: ['kling'], operation: ['motionCreate'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['motionCreate'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['motionCreate'] } },
	},

	// textToImage (KOLORS)
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The image prompt',
		displayOptions: { show: { resource: ['kling'], operation: ['textToImage'] } },
	},
	{
		displayName: 'Negative Prompt',
		name: 'negative_prompt',
		type: 'string',
		default: '',
		description: 'What to avoid in the image',
		displayOptions: { show: { resource: ['kling'], operation: ['textToImage'] } },
	},
	{
		displayName: 'Aspect Ratio',
		name: 'aspect_ratio',
		type: 'options',
		options: [
			{ name: '1:1', value: '1:1' },
			{ name: '16:9', value: '16:9' },
			{ name: '9:16', value: '9:16' },
			{ name: '4:3', value: '4:3' },
			{ name: '3:4', value: '3:4' },
		],
		default: '1:1',
		description: 'Image aspect ratio',
		displayOptions: { show: { resource: ['kling'], operation: ['textToImage'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['textToImage'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['textToImage'] } },
	},

	// omniImage
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The image prompt',
		displayOptions: { show: { resource: ['kling'], operation: ['omniImage'] } },
	},
	{
		displayName: 'Image URL',
		name: 'image_url',
		type: 'string',
		default: '',
		description: 'Optional input image for image-to-image',
		displayOptions: { show: { resource: ['kling'], operation: ['omniImage'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Kling V3', value: 'kling-v3' },
			{ name: 'Kling O1', value: 'kling-o1' },
		],
		default: 'kling-v3',
		description: 'Model version',
		displayOptions: { show: { resource: ['kling'], operation: ['omniImage'] } },
	},
	{
		displayName: 'Aspect Ratio',
		name: 'aspect_ratio',
		type: 'options',
		options: [
			{ name: '1:1', value: '1:1' },
			{ name: '16:9', value: '16:9' },
			{ name: '9:16', value: '9:16' },
			{ name: '4:3', value: '4:3' },
			{ name: '3:4', value: '3:4' },
		],
		default: '1:1',
		description: 'Image aspect ratio',
		displayOptions: { show: { resource: ['kling'], operation: ['omniImage'] } },
	},
	{
		displayName: 'Resolution',
		name: 'resolution',
		type: 'options',
		options: [
			{ name: '1K', value: '1k' },
			{ name: '2K', value: '2k' },
			{ name: '4K', value: '4k' },
		],
		default: '1k',
		description: 'Image resolution',
		displayOptions: { show: { resource: ['kling'], operation: ['omniImage'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['omniImage'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['omniImage'] } },
	},

	// virtualTryOn
	{
		displayName: 'Human Image URL',
		name: 'human_image_url',
		type: 'string',
		required: true,
		default: '',
		description: 'URL of the person image',
		displayOptions: { show: { resource: ['kling'], operation: ['virtualTryOn'] } },
	},
	{
		displayName: 'Cloth Image URL',
		name: 'cloth_image_url',
		type: 'string',
		required: true,
		default: '',
		description: 'URL of the clothing image',
		displayOptions: { show: { resource: ['kling'], operation: ['virtualTryOn'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['virtualTryOn'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['virtualTryOn'] } },
	},

	// recognizeFaces
	{
		displayName: 'Image URL',
		name: 'image_url',
		type: 'string',
		required: true,
		default: '',
		description: 'URL of the image to analyze',
		displayOptions: { show: { resource: ['kling'], operation: ['recognizeFaces'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['recognizeFaces'] } },
	},

	// upscaleImage
	{
		displayName: 'Task ID',
		name: 'task_id',
		type: 'string',
		required: true,
		default: '',
		description: 'Source image task ID',
		displayOptions: { show: { resource: ['kling'], operation: ['upscaleImage'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['upscaleImage'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['upscaleImage'] } },
	},

	// textToSpeech
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		required: true,
		default: '',
		description: 'Text to convert to speech',
		displayOptions: { show: { resource: ['kling'], operation: ['textToSpeech'] } },
	},
	{
		displayName: 'Voice ID',
		name: 'voice_id',
		type: 'string',
		default: '',
		description: 'Voice ID from List TTS Voices',
		displayOptions: { show: { resource: ['kling'], operation: ['textToSpeech'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['textToSpeech'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['textToSpeech'] } },
	},

	// avatarVideo
	{
		displayName: 'Avatar ID',
		name: 'avatar_id',
		type: 'string',
		required: true,
		default: '',
		description: 'Avatar ID from List Avatars',
		displayOptions: { show: { resource: ['kling'], operation: ['avatarVideo'] } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		default: '',
		description: 'TTS text for the avatar',
		displayOptions: { show: { resource: ['kling'], operation: ['avatarVideo'] } },
	},
	{
		displayName: 'Audio URL',
		name: 'audio_url',
		type: 'string',
		default: '',
		description: 'Audio URL (alternative to text)',
		displayOptions: { show: { resource: ['kling'], operation: ['avatarVideo'] } },
	},
	{
		displayName: 'Voice ID',
		name: 'voice_id',
		type: 'string',
		default: '',
		description: 'Voice ID from List TTS Voices',
		displayOptions: { show: { resource: ['kling'], operation: ['avatarVideo'] } },
	},
	{
		displayName: 'Mode',
		name: 'mode',
		type: 'options',
		options: [
			{ name: 'Standard', value: 'std' },
			{ name: 'Professional', value: 'pro' },
		],
		default: 'std',
		description: 'Generation mode',
		displayOptions: { show: { resource: ['kling'], operation: ['avatarVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Kling account to use',
		displayOptions: { show: { resource: ['kling'], operation: ['avatarVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the task completes',
		displayOptions: { show: { resource: ['kling'], operation: ['avatarVideo'] } },
	},

	// getTask
	{
		displayName: 'Task ID',
		name: 'task_id',
		type: 'string',
		required: true,
		default: '',
		description: 'The task ID to retrieve',
		displayOptions: { show: { resource: ['kling'], operation: ['getTask'] } },
	},

	// listTasks
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Filter tasks by account',
		displayOptions: { show: { resource: ['kling'], operation: ['listTasks'] } },
	},

	// cancelTask
	{
		displayName: 'Task ID',
		name: 'task_id',
		type: 'string',
		required: true,
		default: '',
		description: 'The task ID to cancel',
		displayOptions: { show: { resource: ['kling'], operation: ['cancelTask'] } },
	},

	// uploadAsset
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		required: true,
		default: '',
		description: 'URL of asset to upload to Kling',
		displayOptions: { show: { resource: ['kling'], operation: ['uploadAsset'] } },
	},
];

// ──────────────────────────────────────────────────────────────
// Runway operations + fields
// ──────────────────────────────────────────────────────────────

export const runwayOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['runway'] } },
	options: [
		{ name: 'Create Video', value: 'createVideo', description: 'Create a video', action: 'Create a video' },
		{ name: 'Create Image', value: 'createImage', description: 'Create an image', action: 'Create an image' },
		{ name: 'Lip Sync', value: 'lipSync', description: 'Add lip sync to a video', action: 'Lip sync video' },
		{ name: 'Act Two', value: 'actTwo', description: 'Transfer motion from reference video', action: 'Act two motion transfer' },
		{ name: 'Frames', value: 'frames', description: 'Create frames', action: 'Create frames' },
		{ name: 'Get Job', value: 'getJob', description: 'Get job status', action: 'Get job status' },
		{ name: 'List Accounts', value: 'listAccounts', description: 'List all Runway accounts', action: 'List accounts' },
	],
	default: 'createVideo',
};

export const runwayFields: INodeProperties[] = [
	// createVideo
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The video prompt',
		displayOptions: { show: { resource: ['runway'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Gen4 Turbo', value: 'gen4_turbo' },
			{ name: 'Gen4', value: 'gen4' },
			{ name: 'Gen3a Turbo', value: 'gen3a_turbo' },
		],
		default: 'gen4_turbo',
		description: 'Video generation model',
		displayOptions: { show: { resource: ['runway'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Ratio',
		name: 'ratio',
		type: 'options',
		options: [
			{ name: '1280:768 (Landscape)', value: '1280:768' },
			{ name: '768:1280 (Portrait)', value: '768:1280' },
			{ name: '1104:832', value: '1104:832' },
			{ name: '832:1104', value: '832:1104' },
			{ name: '960:960 (Square)', value: '960:960' },
			{ name: '1584:672 (Ultrawide)', value: '1584:672' },
		],
		default: '1280:768',
		description: 'Video aspect ratio',
		displayOptions: { show: { resource: ['runway'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Duration',
		name: 'duration',
		type: 'options',
		options: [
			{ name: '5 Seconds', value: 5 },
			{ name: '10 Seconds', value: 10 },
		],
		default: 5,
		description: 'Video duration in seconds',
		displayOptions: { show: { resource: ['runway'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Image URL',
		name: 'image_url',
		type: 'string',
		default: '',
		description: 'Optional input image for image-to-video generation',
		displayOptions: { show: { resource: ['runway'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Seed',
		name: 'seed',
		type: 'number',
		default: 0,
		description: 'Seed value for reproducibility (0 = random)',
		displayOptions: { show: { resource: ['runway'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Explore Mode',
		name: 'exploreMode',
		type: 'boolean',
		default: false,
		description: 'Whether to use explore mode (unlimited plan only, free generation)',
		displayOptions: { show: { resource: ['runway'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Runway account to use',
		displayOptions: { show: { resource: ['runway'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['runway'], operation: ['createVideo'] } },
	},

	// createImage
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Nano Banana', value: 'nano-banana' },
			{ name: 'Nano Banana 2', value: 'nano-banana-2' },
			{ name: 'Nano Banana Pro', value: 'nano-banana-pro' },
			{ name: 'GPT Image 1.5', value: 'gpt-image-1-5' },
			{ name: 'GPT Image 1 Mini', value: 'gpt-image-1-mini' },
			{ name: 'Seedream 5', value: 'seedream-5' },
			{ name: 'Gen-4', value: 'gen4' },
			{ name: 'Gen-4 Turbo', value: 'gen4-turbo' },
		],
		default: 'nano-banana-pro',
		description: 'Image generation model',
		displayOptions: { show: { resource: ['runway'], operation: ['createImage'] } },
	},
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		default: '',
		description: 'The image prompt (required for GPT Image models, optional for others)',
		displayOptions: { show: { resource: ['runway'], operation: ['createImage'] } },
	},
	{
		displayName: 'Ratio',
		name: 'ratio',
		type: 'options',
		options: [
			{ name: '1:1', value: '1:1' },
			{ name: '16:9', value: '16:9' },
			{ name: '9:16', value: '9:16' },
			{ name: '4:3', value: '4:3' },
			{ name: '3:4', value: '3:4' },
			{ name: '3:2', value: '3:2' },
			{ name: '2:3', value: '2:3' },
			{ name: '21:9', value: '21:9' },
		],
		default: '16:9',
		description: 'Image aspect ratio',
		displayOptions: { show: { resource: ['runway'], operation: ['createImage'] } },
	},
	{
		displayName: 'Seed',
		name: 'seed',
		type: 'number',
		default: 0,
		description: 'Seed value for reproducibility (0 = random)',
		displayOptions: { show: { resource: ['runway'], operation: ['createImage'] } },
	},
	{
		displayName: 'Explore Mode',
		name: 'exploreMode',
		type: 'boolean',
		default: false,
		description: 'Whether to use explore mode (unlimited plan only)',
		displayOptions: { show: { resource: ['runway'], operation: ['createImage'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Runway account to use',
		displayOptions: { show: { resource: ['runway'], operation: ['createImage'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['runway'], operation: ['createImage'] } },
	},

	// lipSync
	{
		displayName: 'Video URL',
		name: 'video_url',
		type: 'string',
		required: true,
		default: '',
		description: 'Source video URL or job URL',
		displayOptions: { show: { resource: ['runway'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Audio URL',
		name: 'audio_url',
		type: 'string',
		default: '',
		description: 'Audio URL for lip sync',
		displayOptions: { show: { resource: ['runway'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		default: '',
		description: 'Text for TTS lip sync',
		displayOptions: { show: { resource: ['runway'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Runway account to use',
		displayOptions: { show: { resource: ['runway'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['runway'], operation: ['lipSync'] } },
	},

	// actTwo
	{
		displayName: 'Video URL',
		name: 'video_url',
		type: 'string',
		required: true,
		default: '',
		description: 'Source video URL',
		displayOptions: { show: { resource: ['runway'], operation: ['actTwo'] } },
	},
	{
		displayName: 'Reference URL',
		name: 'reference_url',
		type: 'string',
		required: true,
		default: '',
		description: 'Reference video for motion transfer',
		displayOptions: { show: { resource: ['runway'], operation: ['actTwo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Runway account to use',
		displayOptions: { show: { resource: ['runway'], operation: ['actTwo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['runway'], operation: ['actTwo'] } },
	},

	// frames
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The frames prompt',
		displayOptions: { show: { resource: ['runway'], operation: ['frames'] } },
	},
	{
		displayName: 'Image URL',
		name: 'image_url',
		type: 'string',
		default: '',
		description: 'Optional input image',
		displayOptions: { show: { resource: ['runway'], operation: ['frames'] } },
	},
	{
		displayName: 'Last Frame URL',
		name: 'last_frame_url',
		type: 'string',
		default: '',
		description: 'Optional last frame image URL',
		displayOptions: { show: { resource: ['runway'], operation: ['frames'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Gen4 Turbo', value: 'gen4_turbo' },
		],
		default: 'gen4_turbo',
		description: 'Model version',
		displayOptions: { show: { resource: ['runway'], operation: ['frames'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Runway account to use',
		displayOptions: { show: { resource: ['runway'], operation: ['frames'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['runway'], operation: ['frames'] } },
	},

	// getJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The job ID to retrieve',
		displayOptions: { show: { resource: ['runway'], operation: ['getJob'] } },
	},
];

// ──────────────────────────────────────────────────────────────
// PixVerse operations + fields
// ──────────────────────────────────────────────────────────────

export const pixverseOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['pixverse'] } },
	options: [
		{ name: 'Create Video', value: 'createVideo', description: 'Create a video', action: 'Create a video' },
		{ name: 'Create Image', value: 'createImage', description: 'Create an image', action: 'Create an image' },
		{ name: 'Extend Video', value: 'extendVideo', description: 'Extend a video', action: 'Extend video' },
		{ name: 'Upscale Video', value: 'upscaleVideo', description: 'Upscale a video', action: 'Upscale video' },
		{ name: 'Lip Sync', value: 'lipSync', description: 'Add lip sync to a video', action: 'Lip sync video' },
		{ name: 'Modify Video', value: 'modifyVideo', description: 'Modify a video with a prompt', action: 'Modify video' },
		{ name: 'Get Job', value: 'getJob', description: 'Get job status', action: 'Get job status' },
		{ name: 'List Accounts', value: 'listAccounts', description: 'List all PixVerse accounts', action: 'List accounts' },
	],
	default: 'createVideo',
};

export const pixverseFields: INodeProperties[] = [
	// createVideo
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The video prompt',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Negative Prompt',
		name: 'negative_prompt',
		type: 'string',
		default: '',
		description: 'What to avoid in the video',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'V5.6', value: 'v5.6' },
			{ name: 'V5.5', value: 'v5.5' },
			{ name: 'V5', value: 'v5' },
			{ name: 'V5 Fast', value: 'v5-fast' },
		],
		default: 'v5.6',
		description: 'Video generation model',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Aspect Ratio',
		name: 'aspect_ratio',
		type: 'options',
		options: [
			{ name: '16:9', value: '16:9' },
			{ name: '9:16', value: '9:16' },
			{ name: '1:1', value: '1:1' },
			{ name: '4:3', value: '4:3' },
			{ name: '3:4', value: '3:4' },
		],
		default: '16:9',
		description: 'Video aspect ratio',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Duration',
		name: 'duration',
		type: 'options',
		options: [
			{ name: '5 Seconds', value: 5 },
			{ name: '8 Seconds', value: 8 },
		],
		default: 5,
		description: 'Video duration in seconds',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Quality',
		name: 'quality',
		type: 'options',
		options: [
			{ name: '540p', value: '540p' },
			{ name: '720p', value: '720p' },
			{ name: '1080p', value: '1080p' },
		],
		default: '720p',
		description: 'Video quality',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Seed',
		name: 'seed',
		type: 'number',
		default: 0,
		description: 'Seed value for reproducibility (0 = random)',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Image URL',
		name: 'image_url',
		type: 'string',
		default: '',
		description: 'Optional input image for image-to-video generation',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific PixVerse account to use',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createVideo'] } },
	},

	// createImage
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The image prompt',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createImage'] } },
	},
	{
		displayName: 'Negative Prompt',
		name: 'negative_prompt',
		type: 'string',
		default: '',
		description: 'What to avoid in the image',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createImage'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Seedream V3', value: 'seedream-v3' },
			{ name: 'Nano Banana', value: 'nano-banana' },
			{ name: 'Qwen VL', value: 'qwen-vl' },
		],
		default: 'seedream-v3',
		description: 'Image generation model',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createImage'] } },
	},
	{
		displayName: 'Aspect Ratio',
		name: 'aspect_ratio',
		type: 'options',
		options: [
			{ name: '1:1', value: '1:1' },
			{ name: '16:9', value: '16:9' },
			{ name: '9:16', value: '9:16' },
			{ name: '4:3', value: '4:3' },
			{ name: '3:4', value: '3:4' },
		],
		default: '1:1',
		description: 'Image aspect ratio',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createImage'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific PixVerse account to use',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createImage'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['pixverse'], operation: ['createImage'] } },
	},

	// extendVideo
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'Source video job ID',
		displayOptions: { show: { resource: ['pixverse'], operation: ['extendVideo'] } },
	},
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		default: '',
		description: 'Optional prompt for extension',
		displayOptions: { show: { resource: ['pixverse'], operation: ['extendVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific PixVerse account to use',
		displayOptions: { show: { resource: ['pixverse'], operation: ['extendVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['pixverse'], operation: ['extendVideo'] } },
	},

	// upscaleVideo
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'Source video job ID',
		displayOptions: { show: { resource: ['pixverse'], operation: ['upscaleVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific PixVerse account to use',
		displayOptions: { show: { resource: ['pixverse'], operation: ['upscaleVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['pixverse'], operation: ['upscaleVideo'] } },
	},

	// lipSync
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'Source video job ID',
		displayOptions: { show: { resource: ['pixverse'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Audio URL',
		name: 'audio_url',
		type: 'string',
		default: '',
		description: 'Audio URL for lip sync',
		displayOptions: { show: { resource: ['pixverse'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		default: '',
		description: 'Text for TTS lip sync',
		displayOptions: { show: { resource: ['pixverse'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific PixVerse account to use',
		displayOptions: { show: { resource: ['pixverse'], operation: ['lipSync'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['pixverse'], operation: ['lipSync'] } },
	},

	// modifyVideo
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'Source video job ID',
		displayOptions: { show: { resource: ['pixverse'], operation: ['modifyVideo'] } },
	},
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'Modification prompt',
		displayOptions: { show: { resource: ['pixverse'], operation: ['modifyVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific PixVerse account to use',
		displayOptions: { show: { resource: ['pixverse'], operation: ['modifyVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['pixverse'], operation: ['modifyVideo'] } },
	},

	// getJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The job ID to retrieve',
		displayOptions: { show: { resource: ['pixverse'], operation: ['getJob'] } },
	},
];

// ──────────────────────────────────────────────────────────────
// MiniMax operations + fields
// ──────────────────────────────────────────────────────────────

export const minimaxOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['minimax'] } },
	options: [
		{ name: 'Create Video', value: 'createVideo', description: 'Create a video', action: 'Create a video' },
		{ name: 'Create Image', value: 'createImage', description: 'Create an image', action: 'Create an image' },
		{ name: 'Create Music', value: 'createMusic', description: 'Create music from a prompt', action: 'Create music' },
		{ name: 'Get Video Job', value: 'getVideoJob', description: 'Get video job status', action: 'Get video job' },
		{ name: 'Get Image Job', value: 'getImageJob', description: 'Get image job status', action: 'Get image job' },
		{ name: 'List Accounts', value: 'listAccounts', description: 'List all MiniMax accounts', action: 'List accounts' },
	],
	default: 'createVideo',
};

export const minimaxFields: INodeProperties[] = [
	// createVideo
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The video prompt',
		displayOptions: { show: { resource: ['minimax'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Hailuo 02', value: 'hailuo-02' },
			{ name: 'Hailuo 01 Pro', value: 'hailuo-01-pro' },
			{ name: 'Hailuo 01', value: 'hailuo-01' },
			{ name: 'Hailuo 01 Live2D', value: 'hailuo-01-live2d' },
			{ name: 'Veo 3', value: 'veo-3' },
			{ name: 'Sora 2', value: 'sora-2' },
			{ name: 'Hailuo MJ', value: 'hailuo-mj' },
		],
		default: 'hailuo-02',
		description: 'Video generation model',
		displayOptions: { show: { resource: ['minimax'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Resolution',
		name: 'resolution',
		type: 'options',
		options: [
			{ name: '1080p', value: '1080p' },
			{ name: '720p', value: '720p' },
			{ name: '480p', value: '480p' },
		],
		default: '1080p',
		description: 'Video resolution',
		displayOptions: { show: { resource: ['minimax'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Duration',
		name: 'duration',
		type: 'options',
		options: [
			{ name: '6 Seconds', value: 6 },
			{ name: '9 Seconds', value: 9 },
		],
		default: 6,
		description: 'Video duration in seconds',
		displayOptions: { show: { resource: ['minimax'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Image URL',
		name: 'image_url',
		type: 'string',
		default: '',
		description: 'Optional input image for image-to-video generation',
		displayOptions: { show: { resource: ['minimax'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific MiniMax account to use',
		displayOptions: { show: { resource: ['minimax'], operation: ['createVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['minimax'], operation: ['createVideo'] } },
	},

	// createImage
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The image prompt',
		displayOptions: { show: { resource: ['minimax'], operation: ['createImage'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Hailuo MJ', value: 'hailuo-mj' },
			{ name: 'Midjourney', value: 'midjourney' },
			{ name: 'Gemini Image', value: 'gemini-image' },
			{ name: 'GPT Image', value: 'gpt-image' },
			{ name: 'Seedream', value: 'seedream' },
		],
		default: 'hailuo-mj',
		description: 'Image generation model',
		displayOptions: { show: { resource: ['minimax'], operation: ['createImage'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific MiniMax account to use',
		displayOptions: { show: { resource: ['minimax'], operation: ['createImage'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['minimax'], operation: ['createImage'] } },
	},

	// createMusic
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The music prompt',
		displayOptions: { show: { resource: ['minimax'], operation: ['createMusic'] } },
	},
	{
		displayName: 'Lyrics',
		name: 'lyrics',
		type: 'string',
		default: '',
		description: 'Optional lyrics for the music',
		displayOptions: { show: { resource: ['minimax'], operation: ['createMusic'] } },
	},
	{
		displayName: 'Instrumental',
		name: 'instrumental',
		type: 'boolean',
		default: false,
		description: 'Whether to generate instrumental only',
		displayOptions: { show: { resource: ['minimax'], operation: ['createMusic'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific MiniMax account to use',
		displayOptions: { show: { resource: ['minimax'], operation: ['createMusic'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['minimax'], operation: ['createMusic'] } },
	},

	// getVideoJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The video job ID to retrieve',
		displayOptions: { show: { resource: ['minimax'], operation: ['getVideoJob'] } },
	},

	// getImageJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The image job ID to retrieve',
		displayOptions: { show: { resource: ['minimax'], operation: ['getImageJob'] } },
	},
];

// ──────────────────────────────────────────────────────────────
// InsightFaceSwap operations + fields
// ──────────────────────────────────────────────────────────────

export const insightfaceswapOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['insightfaceswap'] } },
	options: [
		{ name: 'Swap Face', value: 'swapFace', description: 'Swap a face between two images', action: 'Swap a face' },
		{ name: 'Get Job', value: 'getJob', description: 'Get job status', action: 'Get job status' },
		{ name: 'List Accounts', value: 'listAccounts', description: 'List all InsightFaceSwap accounts', action: 'List accounts' },
	],
	default: 'swapFace',
};

export const insightfaceswapFields: INodeProperties[] = [
	// swapFace
	{
		displayName: 'Target Image URL',
		name: 'target',
		type: 'string',
		required: true,
		default: '',
		description: 'URL of the target image (body to keep)',
		displayOptions: { show: { resource: ['insightfaceswap'], operation: ['swapFace'] } },
	},
	{
		displayName: 'Source Image URL',
		name: 'source',
		type: 'string',
		required: true,
		default: '',
		description: 'URL of the source face image (face to swap in)',
		displayOptions: { show: { resource: ['insightfaceswap'], operation: ['swapFace'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific InsightFaceSwap account to use',
		displayOptions: { show: { resource: ['insightfaceswap'], operation: ['swapFace'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['insightfaceswap'], operation: ['swapFace'] } },
	},

	// getJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The job ID to retrieve',
		displayOptions: { show: { resource: ['insightfaceswap'], operation: ['getJob'] } },
	},
];

// ──────────────────────────────────────────────────────────────
// Google Flow operations + fields
// ──────────────────────────────────────────────────────────────

export const googleFlowOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['googleFlow'] } },
	options: [
		{ name: 'Generate Image', value: 'generateImage', description: 'Generate an image from a prompt', action: 'Generate an image' },
		{ name: 'Upscale Image', value: 'upscaleImage', description: 'Upscale a generated image', action: 'Upscale an image' },
		{ name: 'Generate Video', value: 'generateVideo', description: 'Generate a video from a prompt', action: 'Generate a video' },
		{ name: 'Concatenate Videos', value: 'concatenateVideos', description: 'Concatenate multiple videos', action: 'Concatenate videos' },
		{ name: 'Extend Video', value: 'extendVideo', description: 'Extend a video', action: 'Extend video' },
		{ name: 'To GIF', value: 'toGif', description: 'Convert a video to GIF', action: 'Convert to GIF' },
		{ name: 'Upscale Video', value: 'upscaleVideo', description: 'Upscale a video', action: 'Upscale a video' },
		{ name: 'Get Job', value: 'getJob', description: 'Get job status', action: 'Get job status' },
		{ name: 'List Jobs', value: 'listJobs', description: 'List jobs', action: 'List jobs' },
		{ name: 'Cancel Job', value: 'cancelJob', description: 'Cancel a running job', action: 'Cancel a job' },
		{ name: 'List Assets', value: 'listAssets', description: 'List assets', action: 'List assets' },
		{ name: 'List Assets by Account', value: 'listAssetsByAccount', description: 'List assets for a specific account', action: 'List assets by account' },
		{ name: 'Delete Asset', value: 'deleteAsset', description: 'Delete an asset', action: 'Delete asset' },
		{ name: 'Add Account', value: 'addAccount', description: 'Add a Google Flow account', action: 'Add account' },
		{ name: 'Get Account', value: 'getAccount', description: 'Get account details', action: 'Get account' },
		{ name: 'List Accounts', value: 'listAccounts', description: 'List all Google Flow accounts', action: 'List accounts' },
		{ name: 'Delete Account', value: 'deleteAccount', description: 'Delete a Google Flow account', action: 'Delete account' },
		{ name: 'Configure Captcha', value: 'configureCaptcha', description: 'Configure captcha provider for an account', action: 'Configure captcha' },
		{ name: 'List Captcha Providers', value: 'listCaptchaProviders', description: 'List configured captcha providers', action: 'List captcha providers' },
		{ name: 'Get Captcha Stats', value: 'getCaptchaStats', description: 'Get captcha solving statistics', action: 'Get captcha stats' },
	],
	default: 'generateImage',
};

export const googleFlowFields: INodeProperties[] = [
	// generateImage
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The image prompt',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Imagen 4', value: 'imagen-4' },
			{ name: 'Imagen 4 Ultra', value: 'imagen-4-ultra' },
			{ name: 'Nano Banana', value: 'nano-banana' },
		],
		default: 'imagen-4',
		description: 'Image generation model',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Aspect Ratio',
		name: 'aspect_ratio',
		type: 'options',
		options: [
			{ name: '16:9', value: '16:9' },
			{ name: '9:16', value: '9:16' },
			{ name: '1:1', value: '1:1' },
			{ name: '4:3', value: '4:3' },
			{ name: '3:4', value: '3:4' },
		],
		default: '1:1',
		description: 'Image aspect ratio',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Image Count',
		name: 'image_count',
		type: 'number',
		default: 0,
		description: 'Number of images to generate (0 = default)',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Google Flow account to use',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Reply Ref',
		name: 'replyRef',
		type: 'string',
		default: '',
		description: 'Custom reference passed back in webhook',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateImage'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateImage'] } },
	},

	// upscaleImage
	{
		displayName: 'Asset ID',
		name: 'assetId',
		type: 'string',
		required: true,
		default: '',
		description: 'Asset ID of the image to upscale',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['upscaleImage'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Google Flow account to use',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['upscaleImage'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['upscaleImage'] } },
	},

	// generateVideo
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		required: true,
		default: '',
		description: 'The video prompt',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Model',
		name: 'model',
		type: 'options',
		options: [
			{ name: 'Veo 3', value: 'veo-3' },
			{ name: 'Veo 3 Fast', value: 'veo-3-fast' },
			{ name: 'Veo 2', value: 'veo-2' },
		],
		default: 'veo-3',
		description: 'Video generation model',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Aspect Ratio',
		name: 'aspect_ratio',
		type: 'options',
		options: [
			{ name: '16:9', value: '16:9' },
			{ name: '9:16', value: '9:16' },
			{ name: '1:1', value: '1:1' },
			{ name: '4:3', value: '4:3' },
			{ name: '3:4', value: '3:4' },
		],
		default: '16:9',
		description: 'Video aspect ratio',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Duration',
		name: 'duration',
		type: 'number',
		default: 0,
		description: 'Video duration in seconds (0 = default)',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Seed',
		name: 'seed',
		type: 'number',
		default: 0,
		description: 'Seed value for reproducibility (0 = random)',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Image URL',
		name: 'image_url',
		type: 'string',
		default: '',
		description: 'Optional input image for image-to-video generation',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Google Flow account to use',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Reply Ref',
		name: 'replyRef',
		type: 'string',
		default: '',
		description: 'Custom reference passed back in webhook',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['generateVideo'] } },
	},

	// concatenateVideos
	{
		displayName: 'Asset IDs',
		name: 'assetIds',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated asset IDs of videos to concatenate',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['concatenateVideos'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Google Flow account to use',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['concatenateVideos'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['concatenateVideos'] } },
	},

	// extendVideo
	{
		displayName: 'Asset ID',
		name: 'assetId',
		type: 'string',
		required: true,
		default: '',
		description: 'Asset ID of the video to extend',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['extendVideo'] } },
	},
	{
		displayName: 'Prompt',
		name: 'prompt',
		type: 'string',
		default: '',
		description: 'Optional prompt for extension',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['extendVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Google Flow account to use',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['extendVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['extendVideo'] } },
	},

	// toGif
	{
		displayName: 'Asset ID',
		name: 'assetId',
		type: 'string',
		required: true,
		default: '',
		description: 'Asset ID of the video to convert to GIF',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['toGif'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Google Flow account to use',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['toGif'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['toGif'] } },
	},

	// upscaleVideo
	{
		displayName: 'Asset ID',
		name: 'assetId',
		type: 'string',
		required: true,
		default: '',
		description: 'Asset ID of the video to upscale',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['upscaleVideo'] } },
	},
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Specific Google Flow account to use',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['upscaleVideo'] } },
	},
	{
		displayName: 'Wait for Completion',
		name: 'waitForCompletion',
		type: 'boolean',
		default: true,
		description: 'Whether to poll until the job completes',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['upscaleVideo'] } },
	},

	// getJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The job ID to retrieve',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['getJob'] } },
	},

	// listJobs
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Filter jobs by account',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['listJobs'] } },
	},
	{
		displayName: 'Status',
		name: 'status',
		type: 'options',
		options: [
			{ name: 'All', value: '' },
			{ name: 'Created', value: 'created' },
			{ name: 'Started', value: 'started' },
			{ name: 'Completed', value: 'completed' },
			{ name: 'Failed', value: 'failed' },
		],
		default: '',
		description: 'Filter jobs by status',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['listJobs'] } },
	},

	// cancelJob
	{
		displayName: 'Job ID',
		name: 'jobid',
		type: 'string',
		required: true,
		default: '',
		description: 'The job ID to cancel',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['cancelJob'] } },
	},

	// listAssets
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		default: '',
		description: 'Filter assets by account',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['listAssets'] } },
	},

	// listAssetsByAccount
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		required: true,
		default: '',
		description: 'Account to list assets for',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['listAssetsByAccount'] } },
	},

	// deleteAsset
	{
		displayName: 'Asset ID',
		name: 'assetId',
		type: 'string',
		required: true,
		default: '',
		description: 'The asset ID to delete',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['deleteAsset'] } },
	},

	// addAccount
	{
		displayName: 'Cookies',
		name: 'cookies',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		description: 'Browser cookies for Google Flow authentication',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['addAccount'] } },
	},
	{
		displayName: 'Max Jobs',
		name: 'maxJobs',
		type: 'number',
		default: 0,
		description: 'Maximum concurrent jobs (0 = default)',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['addAccount'] } },
	},

	// getAccount
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		required: true,
		default: '',
		description: 'Account identifier',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['getAccount'] } },
	},

	// deleteAccount
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		required: true,
		default: '',
		description: 'Account identifier to delete',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['deleteAccount'] } },
	},

	// configureCaptcha
	{
		displayName: 'Account',
		name: 'account',
		type: 'string',
		required: true,
		default: '',
		description: 'Account to configure captcha for',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['configureCaptcha'] } },
	},
	{
		displayName: 'Provider',
		name: 'provider',
		type: 'string',
		required: true,
		default: '',
		description: 'Captcha provider name',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['configureCaptcha'] } },
	},
	{
		displayName: 'API Key',
		name: 'apiKey',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		description: 'Captcha provider API key',
		displayOptions: { show: { resource: ['googleFlow'], operation: ['configureCaptcha'] } },
	},
];
